// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://bzocikmpgvxgpiycwltc.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImJ6b2Npa21wZ3Z4Z3BpeWN3bHRjIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2MzIxMjQsImV4cCI6MjA3MjIwODEyNH0.8_lxmN3_KQmjhsbYggCa_rJsb8pviOmiXOOgM23N8Vg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});